version: '2'
services:
  # InfluxDB:
  #   container_name: influx_db
  #   image: influxdb:2.1.1
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=$influx_mode
  #     - DOCKER_INFLUXDB_INIT_USERNAME=$influx_username
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=$influx_password
  #     - DOCKER_INFLUXDB_INIT_ORG=$influx_org
  #     - DOCKER_INFLUXDB_INIT_BUCKET=$influx_bucket
  #     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$influx_token
  #   ports:
  #   # InfluxDB Web Port - Set to 8081 for local machine
  #     - "8081:8086"

  SolarLogger:
    container_name: solar_logger
    build:
      dockerfile: solar.dockerfile
    image: python:3.9
    network_mode: host
    # ports:
    # #INFLUX PORTS
    #   - "8086:8086"
    #   - "8088:8088"
    # #MQTT PORTS
    #   - "8883:8883"
  
  # InfluxQuery:
  #   container_name: influx_query
  #   build:
  #     dockerfile: query.dockerfile
  #   image: python:3.9
  #   network_mode: host