version: '3.8'
services:
  influx_db:
    container_name: InfluxDB
    image: influxdb:2.1.1
    ports:
      - "8086:8086"
    volumes:
      - ./docker-influxdb/var/lib/influxdb2:/var/lib/influxdb2:rw
      - ./docker-influxdb/etc/influxdb2:/etc/influxdb2:rw
  
  solar_logger:
    container_name: SolarLogger
    build:
      context: ./
      dockerfile: solar.dockerfile
    volumes:
      - ./docker-output:/app/output:rw
    env_file:
      - .env
  
  influx_query:
    container_name: InfluxQuery
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: influx-query.dockerfile
    volumes:
      - ./docker-output:/app/output:rw
    env_file:
      - .env
