version: '3.8'
services:
  influx-db:
    container_name: InfluxDB
    image: influxdb:2.1.1
    ports:
      - "8086:8086"
    volumes:
      - ./docker-influxdb/data-volume:/var/lib/influxdb2:rw
      - ./docker-influxdb/config:/etc/influxdb2:rw

  solar-logger:
    container_name: SolarLogger
    build:
      context: ./
      dockerfile: solar-logger.dockerfile
      target: solar-logger
    volumes:
      - ./output:/solarlogger/output:rw
      - ./config:/solarlogger/config:rw
    env_file:
      - .env
  
  influx-query:
    container_name: InfluxQuery
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: solar-logger.dockerfile
      target: influx-query
    volumes:
      - ./output:/solarlogger/output:rw
    env_file:
      - .env

  unit-tests:
    container_name: UnitTests
    build:
      context: ./
      dockerfile: solar-logger.dockerfile
      target: unit-tests
    env_file:
      - .env
  